site_name: OSG Production
site_url: https://opensciencegrid.github.io/production/
repo_url: https://github.com/opensciencegrid/production/
theme: 
  name: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Weekly Minutes:
  - '9 January 2018': 'WeeklyMinutes/09January2018.md'
  - '2 January 2018 Canceled': 'WeeklyMinutes/Canceled.md'
  - '26 December 2017 Canceled': 'WeeklyMinutes/Canceled.md'
  - '19 December 2017': 'WeeklyMinutes/19December2017.md'
  - '12 December 2017': 'WeeklyMinutes/12December2017.md'
  - '5 December 2017': 'WeeklyMinutes/05December2017.md'
  - '28 November 2017': 'WeeklyMinutes/28November2017.md'
  - '21 November 2017': 'WeeklyMinutes/21November2017.md'
  - '14 November 2017': 'WeeklyMinutes/14November2017.md'
  - '7 November 2017': 'WeeklyMinutes/07November2017.md'
  - '31 October 2017': 'WeeklyMinutes/31October2017.md'
  - '24 October 2017': 'WeeklyMinutes/24October2017.md'
  - '17 October 2017': 'WeeklyMinutes/17October2017.md'
  - '10 October 2017': 'WeeklyMinutes/10October2017.md'
  - '26 September 2017': 'WeeklyMinutes/26Sep2017.md'
  - '19 September 2017': 'WeeklyMinutes/19Sep2017.md'
  - '12 September 2017': 'WeeklyMinutes/12Sep2017.md'
  - '5 September 2017': 'WeeklyMinutes/05Sep2017.md'
  - '29 August 2017': 'WeeklyMinutes/29Aug2017.md'
  - '22 August 2017': 'WeeklyMinutes/22Aug2017.md'
  - '15 August 2017': 'WeeklyMinutes/15Aug2017.md'
  - '8 August 2017': 'WeeklyMinutes/08August2017.md'
  - '1 August 2017': 'WeeklyMinutes/01August2017.md'
  - '25 July 2017': 'WeeklyMinutes/25July2017.md'
  - '18 July 2017': 'WeeklyMinutes/18July2017.md'
  - '11 July 2017': 'WeeklyMinutes/11July2017.md'
  - '4 July 2017 Canceled': 'WeeklyMinutes/Canceled.md'
  - '27 June 2017': 'WeeklyMinutes/27June2017.md'
  - '20 June 2017': 'WeeklyMinutes/20June2017.md'
  - '13 June 2017': 'WeeklyMinutes/13June2017.md'
  - '6 June 2017': 'WeeklyMinutes/06June2017.md'
  - '30 May 2017': 'WeeklyMinutes/30May2017.md'
  - '23 May 2017': 'WeeklyMinutes/23May2017.md'
  - '16 May 2017': 'WeeklyMinutes/16May2017.md'
  - '9 May 2017': 'WeeklyMinutes/09May2017.md'
  - '2 May 2017': 'WeeklyMinutes/02May2017.md'
  - '25 April 2017': 'WeeklyMinutes/25April2017.md'
  - '18 April 2017': 'WeeklyMinutes/18April2017.md'
  - '11 April 2017': 'WeeklyMinutes/11April2017.md'
  - '4 April 2017': 'WeeklyMinutes/4April2017.md'
  - '28 March 2017': 'WeeklyMinutes/28March2017.md'
  - '21 March 2017': 'WeeklyMinutes/21March2017.md'
  - '14 March 2017': 'WeeklyMinutes/14March2017.md'
  - '7 March 2017 Canceled': 'WeeklyMinutes/Canceled.md'
  - '28 Februray 2017': 'WeeklyMinutes/28Feb2017.md'
  - '21 February 2017': 'WeeklyMinutes/21Feb2017.md'
  - '14 February 2017': 'WeeklyMinutes/14Feb2017.md'
  - '7 February 2017': 'WeeklyMinutes/14Feb2017.md'
- Weekly Template: 
  - 'Template': 'WeeklyTemplate.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

